
// Mock flight data for Middle Eastern destinations with official airline logo URLs
export const mockFlights = [
  {
    id: 1,
    airline: 'Emirates',
    airlineCode: 'EK',
    airlineLogo: 'https://www.emirates.com/etc/designs/ecom/creative/emirates-logo.png',
    departureCity: 'New York',
    departureCode: 'JFK',
    departureTime: '21:00',
    departureDate: 'Tue, Jun 10',
    arrivalCity: 'Dubai',
    arrivalCode: 'DXB',
    arrivalTime: '07:05',
    arrivalDate: 'Wed, Jun 11',
    duration: '14h 35m',
    stops: 1,
    stopCities: ['London (LHR)'],
    price: 65909,
    baseFare: 1050,
    taxes: 135,
    fees: 60,
    carbonFootprint: '2.3 tonnes',
    tags: ['Best Value'],
    returnFlight: {
      departureCity: 'Dubai',
      departureCode: 'DXB',
      departureTime: '03:30',
      departureDate: 'Tue, Jun 16',
      arrivalCity: 'New York',
      arrivalCode: 'JFK',
      arrivalTime: '09:45',
      arrivalDate: 'Tue, Jun 16',
      duration: '13h 45m',
      stops: 0,
    },
  },
  {
    id: 2,
    airline: 'Air India',
    airlineCode: 'AI',
    airlineLogo: 'https://airindia.com/content/dam/airindia/logos/airindia-logo.svg',
    departureCity: 'New York',
    departureCode: 'JFK',
    departureTime: '14:20',
    departureDate: 'Wed, Jul 5',
    arrivalCity: 'Dubai',
    arrivalCode: 'DXB',
    arrivalTime: '20:20',
    arrivalDate: 'Thu, Jul 6',
    duration: '10h 30m',
    stops: 0,
    stopCities: [],
    price: 59035,
    baseFare: 820,
    taxes: 105,
    fees: 53,
    carbonFootprint: '1.9 tonnes',
    tags: ['Direct Flight', 'Cheapest'],
    returnFlight: {
      departureCity: 'Dubai',
      departureCode: 'DXB',
      departureTime: '10:15',
      departureDate: 'Wed, Jul 12',
      arrivalCity: 'New York',
      arrivalCode: 'JFK',
      arrivalTime: '16:45',
      arrivalDate: 'Wed, Jul 12',
      duration: '14h 30m',
      stops: 1,
      stopCities: ['Delhi (DEL)'],
    },
  },
  {
    id: 3,
    airline: 'Etihad Airways',
    airlineCode: 'EY',
    airlineLogo: 'https://www.etihad.com/content/dam/etihad/global/logo/etihad-logo.svg',
    departureCity: 'New York',
    departureCode: 'JFK',
    departureTime: '10:00',
    departureDate: 'Tue, Sep 8',
    arrivalCity: 'Abu Dhabi',
    arrivalCode: 'AUH',
    arrivalTime: '07:00',
    arrivalDate: 'Wed, Sep 9',
    duration: '25h 30m',
    stops: 1,
    stopCities: ['London (LHR)'],
    price: 45717,
    baseFare: 990,
    taxes: 140,
    fees: 60,
    carbonFootprint: '2.1 tonnes',
    tags: ['Cheapest'],
    returnFlight: {
      departureCity: 'Abu Dhabi',
      departureCode: 'AUH',
      departureTime: '08:50',
      departureDate: 'Tue, Sep 15',
      arrivalCity: 'New York',
      arrivalCode: 'JFK',
      arrivalTime: '14:30',
      arrivalDate: 'Tue, Sep 15',
      duration: '15h 40m',
      stops: 1,
      stopCities: ['London (LHR)'],
    },
  }
];
