name: Visual Regression Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  visual-regression:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Start dev server in background
        run: npm run dev &
        env:
          BROWSER: none

      - name: Wait for dev server
        run: |
          echo "Waiting for dev server to start..."
          npx wait-on http://localhost:8082 -t 60000

      - name: Run Percy visual regression tests
        run: npm run percy:visual
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }} 